name: Install Prometheus and Grafana on EC2

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Updated to v3

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2  # Updated to v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Install SSH client
      run: sudo apt-get install -y openssh-client

    - name: Setup EC2 SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

    - name: Install Prometheus and Grafana on EC2
      run: |
        EC2_PUBLIC_IP=${{ secrets.EC2_PUBLIC_IP }}
        SSH_USER=${{ secrets.EC2_SSH_USER }}

        # Install Prometheus
        ssh -i ~/.ssh/id_rsa $SSH_USER@$EC2_PUBLIC_IP "sudo apt-get update && sudo apt-get install -y curl"
        ssh -i ~/.ssh/id_rsa $SSH_USER@$EC2_PUBLIC_IP "bash -s" << 'PROMETHEUS_EOF'
          # Prometheus installation script
          sudo mkdir -p /etc/prometheus
          sudo mkdir -p /var/lib/prometheus
          curl -LO https://github.com/prometheus/prometheus/releases/download/v2.36.0/prometheus-2.36.0.linux-amd64.tar.gz
          tar -xvzf prometheus-2.36.0.linux-amd64.tar.gz
          sudo mv prometheus-2.36.0.linux-amd64/prometheus /usr/local/bin/
          sudo mv prometheus-2.36.0.linux-amd64/promtool /usr/local/bin/
          sudo mv prometheus-2.36.0.linux-amd64/consoles /etc/prometheus
          sudo mv prometheus-2.36.0.linux-amd64/console_libraries /etc/prometheus
          sudo cp prometheus-2.36.0.linux-amd64/prometheus.yml /etc/prometheus
          sudo rm -rf prometheus-2.36.0.linux-amd64*

          # Create Prometheus service
          sudo tee /etc/systemd/system/prometheus.service > /dev/null << 'SERVICE_EOF'
          [Unit]
          Description=Prometheus
          After=network.target

          [Service]
          User=root
          ExecStart=/usr/local/bin/prometheus --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/var/lib/prometheus/

          [Install]
          WantedBy=multi-user.target
          SERVICE_EOF

          sudo systemctl daemon-reload
          sudo systemctl enable prometheus
          sudo systemctl start prometheus
        PROMETHEUS_EOF

        # Install Grafana
        ssh -i ~/.ssh/id_rsa $SSH_USER@$EC2_PUBLIC_IP "bash -s" << 'GRAFANA_EOF'
          # Grafana installation script
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository "deb https://packages.grafana.com/oss/deb stable main"
          wget -q -O - https://packages.grafana.com/gpg.key | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install -y grafana
          sudo systemctl enable grafana-server
          sudo systemctl start grafana-server
        GRAFANA_EOF

        echo "Prometheus and Grafana are installed and running!"
