name: Test SSH Key

on:
  push:
    branches:
      - main

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "First line:" && head -n 1 ~/.ssh/id_rsa
          echo "Last line:" && tail -n 1 ~/.ssh/id_rsa
          ssh-keygen -y -f ~/.ssh/id_rsa || { echo "SSH key is invalid"; exit 1; }
