- name: Install Prometheus and Grafana on EC2
  run: |
    EC2_PUBLIC_IP=${{ secrets.EC2_PUBLIC_IP }}
    SSH_USER=${{ secrets.EC2_SSH_USER }}

    # Install Prometheus
    ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $SSH_USER@$EC2_PUBLIC_IP << 'EOF'
      set -x  # Enable debugging

      # Ensure required tools are installed
      sudo apt-get update
      sudo apt-get install -y curl tar

      # Create directories
      sudo mkdir -p /etc/prometheus
      sudo mkdir -p /var/lib/prometheus

      # Download and install Prometheus
      curl -LO https://github.com/prometheus/prometheus/releases/download/v2.36.0/prometheus-2.36.0.linux-amd64.tar.gz
      tar -xvzf prometheus-2.36.0.linux-amd64.tar.gz
      sudo mv prometheus-2.36.0.linux-amd64/prometheus /usr/local/bin/
      sudo mv prometheus-2.36.0.linux-amd64/promtool /usr/local/bin/
      sudo mv prometheus-2.36.0.linux-amd64/consoles /etc/prometheus
      sudo mv prometheus-2.36.0.linux-amd64/console_libraries /etc/prometheus
      sudo cp prometheus-2.36.0.linux-amd64/prometheus.yml /etc/prometheus
      sudo rm -rf prometheus-2.36.0.linux-amd64*

      # Create Prometheus service
      sudo bash -c 'cat > /etc/systemd/system/prometheus.service << EOF
      [Unit]
      Description=Prometheus
      After=network.target

      [Service]
      User=root
      ExecStart=/usr/local/bin/prometheus --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/var/lib/prometheus/

      [Install]
      WantedBy=multi-user.target
      EOF'

      # Enable and start Prometheus service
      sudo systemctl enable prometheus
      sudo systemctl start prometheus
    EOF

    # Install Grafana
    ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $SSH_USER@$EC2_PUBLIC_IP << 'EOF'
      set -x  # Enable debugging

      # Install required dependencies for Grafana
      sudo apt-get install -y software-properties-common

      # Add Grafana repository and install Grafana
      sudo add-apt-repository "deb https://packages.grafana.com/oss/deb stable main"
      sudo apt-get update
      sudo apt-get install -y grafana

      # Start Grafana service
      sudo systemctl enable grafana-server
      sudo systemctl start grafana-server
    EOF

    echo "Prometheus and Grafana are installed and running!"
